#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    [ ! -d /var/lib/emcweb/.env ] && virtualenv -p python3 /var/lib/emcweb/.env
    /var/lib/emcweb/.env/bin/pip3 install -r /var/lib/emcweb/requirements.txt || exit 1
    chown -R emc.emc /var/lib/emcweb
    a2enmod socache_shmcb ssl rewrite >/dev/null 2>&1 || true
    a2dissite 000-default default-ssl >/dev/null 2>&1 || true
    a2ensite emcweb >/dev/null 2>&1 || true
    systemctl restart apache2 supervisor redis >/dev/null 2>&1 || true
    systemctl enable  apache2 supervisor redis >/dev/null 2>&1 || true
  ;;
esac

exit 0
