#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    chown -R emc.emc /var/lib/emcweb
    pip3 install Flask Flask-Script Flask-SQLAlchemy Flask-Login Flask-Migrate Flask-Testing Flask-restful Jinja2 SQLAlchemy pyOpenSSL pycrypto PyMySQL Flask-WTF WTForms WTForms-Components requests ujson google-api-python-client oauth2client Celery redis dnspython vine kombu billiard cryptography
    systemctl status apache2 >/dev/null 2>&1 && systemctl restart apache2 >/dev/null 2>&1 || true
    systemctl status supervisor >/dev/null 2>&1 && systemctl restart supervisor >/dev/null 2>&1 || true
  ;;
esac

exit 0
